#!/bin/bash
# Shim for bootupctl that copies Raspberry Pi firmware into the ESP.
# Workaround until https://github.com/coreos/bootupd/issues/651 is resolved.

if [[ $# -ge 2 ]]; then
    if [[ "$1" == "backend" && "$2" == "install" ]]; then
        echo "Copying Raspberry Pi firmware files to ${BASH_ARGV[0]}/boot/efi/" >&2
        cp -av /usr/lib/bootc-raspi-firmwares/. "${BASH_ARGV[0]}"/boot/efi/
        echo "Copying Raspberry Pi firmware files finished" >&2
    fi
fi

exec /usr/bin/bootupctl-orig/bootupctl "$@"
