FROM localhost/onboarding-agent-base:latest

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf install -y \
    kernel-modules-internal \
    kernel-modules-extra

COPY config/config-wifi.json /etc/cockpit/system-onboarding/config.json
