FROM quay.io/fedora/fedora-bootc:43

ARG PLATFORM=rpi4

# Raspberry Pi 4 firmware: install, stage to a known directory, then remove
# the packages. The bootupctl shim copies these files into the ESP at image
# build time. Workaround for https://github.com/coreos/bootupd/issues/651
RUN if [ "$PLATFORM" = "rpi4" ]; then \
    dnf install -y bcm2711-firmware uboot-images-armv8 && \
    cp -P /usr/share/uboot/rpi_arm64/u-boot.bin /boot/efi/rpi-u-boot.bin && \
    mkdir -p /usr/lib/bootc-raspi-firmwares && \
    cp -a /boot/efi/. /usr/lib/bootc-raspi-firmwares/ && \
    dnf remove -y bcm2711-firmware uboot-images-armv8 && \
    mkdir /usr/bin/bootupctl-orig && \
    mv /usr/bin/bootupctl /usr/bin/bootupctl-orig/ && \
    dnf clean all; \
    fi

COPY bootupctl-shim /usr/bin/bootupctl
RUN if [ "$PLATFORM" = "rpi4" ]; then \
    chmod +x /usr/bin/bootupctl && \
    chcon --reference=/usr/bin/bootupctl-orig/bootupctl /usr/bin/bootupctl; \
    fi
COPY config/rpi4-config.txt /boot/efi/config.txt
COPY config/kargs-rpi4.toml /usr/lib/bootc/kargs.d/01-rpi4.toml

# The bootupctl shim is a bash script running in the bootupd_t SELinux domain,
# which triggers denials that the original compiled binary does not. Make the
# domain permissive until upstream bootupd gains native Pi support.
RUN if [ "$PLATFORM" = "rpi4" ]; then \
    dnf install -y policycoreutils-python-utils && \
    semanage permissive -a bootupd_t && \
    dnf remove -y policycoreutils-python-utils && \
    dnf clean all; \
    fi

COPY flightctl-onboarding-*.noarch.rpm /tmp/
RUN --mount=type=cache,target=/var/cache/libdnf5 \
    curl -fsSLo /etc/yum.repos.d/flightctl-fedora.repo https://rpm.flightctl.io/flightctl-fedora.repo \
    && curl -fsSLo /etc/yum.repos.d/flightctl-dev.repo \
    https://copr.fedorainfracloud.org/coprs/g/redhat-et/flightctl-dev/repo/fedora-43/group_redhat-et-flightctl-dev-fedora-43.repo \
    && dnf install -y \
    /tmp/flightctl-onboarding-*.noarch.rpm \
    chrony \
    iw \
    wireless-regdb \
    linux-firmware \
    openssh-server \
    flightctl-agent \
    flightctl-cli \
    && rm -f /tmp/*.rpm

RUN useradd -m -G wheel testadmin \
    && echo "testadmin:testadmin" | chpasswd \
    && echo "testadmin ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/testadmin \
    && chmod 440 /etc/sudoers.d/testadmin \
    && mkdir -p /home/testadmin/.ssh \
    && chmod 700 /home/testadmin/.ssh \
    && chown -R testadmin:testadmin /home/testadmin/.ssh

RUN systemctl enable flightctl-onboarding-setup.service \
    && systemctl enable cockpit.socket \
    && systemctl enable sshd
