FROM quay.io/fedora/fedora-bootc:43

ARG PLATFORM=rpi4

# ---- Raspberry Pi 4 firmware ----

# Install, stage to a known directory, then remove the packages.
# The bootupctl shim copies these files into the ESP at image build time.
# Workaround for https://github.com/coreos/bootupd/issues/651
RUN if [ "$PLATFORM" = "rpi4" ]; then \
    dnf install -y bcm2711-firmware uboot-images-armv8 && \
    cp -P /usr/share/uboot/rpi_arm64/u-boot.bin /boot/efi/rpi-u-boot.bin && \
    mkdir -p /usr/lib/bootc-raspi-firmwares && \
    cp -a /boot/efi/. /usr/lib/bootc-raspi-firmwares/ && \
    dnf remove -y bcm2711-firmware uboot-images-armv8 && \
    mkdir /usr/bin/bootupctl-orig && \
    mv /usr/bin/bootupctl /usr/bin/bootupctl-orig/ && \
    dnf clean all; \
    fi

COPY bootupctl-shim /usr/bin/bootupctl
RUN if [ "$PLATFORM" = "rpi4" ]; then \
    chmod +x /usr/bin/bootupctl && \
    chcon --reference=/usr/bin/bootupctl-orig/bootupctl /usr/bin/bootupctl; \
    fi
COPY config/rpi4-config.txt /boot/efi/config.txt
COPY config/kargs-rpi4.toml /usr/lib/bootc/kargs.d/01-rpi4.toml

# The bootupctl shim is a bash script running in the bootupd_t SELinux domain,
# which triggers denials that the original compiled binary does not. Make the
# domain permissive until upstream bootupd gains native Pi support.
RUN if [ "$PLATFORM" = "rpi4" ]; then \
    dnf install -y policycoreutils-python-utils && \
    semanage permissive -a bootupd_t && \
    dnf remove -y policycoreutils-python-utils && \
    dnf clean all; \
    fi

# ---- cached layers (stable dependencies) ----

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    curl -fsSLo /etc/yum.repos.d/flightctl-fedora.repo https://rpm.flightctl.io/flightctl-fedora.repo \
    && curl -fsSLo /etc/yum.repos.d/flightctl-dev.repo \
    https://copr.fedorainfracloud.org/coprs/g/redhat-et/flightctl-dev/repo/fedora-43/group_redhat-et-flightctl-dev-fedora-43.repo \
    && dnf install -y \
    flightctl-services-1.2.0 \
    flightctl-cli

COPY config/preload-quadlet-images.sh /tmp/preload-quadlet-images.sh
RUN /tmp/preload-quadlet-images.sh && rm -f /tmp/preload-quadlet-images.sh

RUN useradd -m -G wheel testadmin \
    && echo "testadmin:testadmin" | chpasswd \
    && echo "testadmin ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/testadmin \
    && chmod 440 /etc/sudoers.d/testadmin \
    && mkdir -p /home/testadmin/.ssh \
    && chmod 700 /home/testadmin/.ssh \
    && chown -R testadmin:testadmin /home/testadmin/.ssh

COPY config/flightctl-setup-admin.sh /usr/local/bin/flightctl-setup-admin.sh
COPY config/flightctl-setup-admin.service /etc/systemd/system/flightctl-setup-admin.service
RUN chmod +x /usr/local/bin/flightctl-setup-admin.sh

RUN systemctl enable flightctl.target \
    && systemctl enable sshd \
    && systemctl enable flightctl-setup-admin.service \
    && systemctl mask greenboot-healthcheck.service \
    && systemctl mask greenboot-reboot.service

# ---- cache-busting layers (change frequently) ----

RUN mkdir -p /etc/flightctl/pki
COPY config/pki/ca.crt /etc/flightctl/pki/ca.crt
COPY config/pki/ca.key /etc/flightctl/pki/ca.key
RUN chmod 644 /etc/flightctl/pki/ca.crt \
    && chmod 600 /etc/flightctl/pki/ca.key

COPY config/service-config.yaml /etc/flightctl/service-config.yaml

RUN echo "flightctl.internal" > /etc/hostname

RUN mkdir -p /etc/NetworkManager/system-connections
COPY config/server-ethernet.nmconnection /etc/NetworkManager/system-connections/server-ethernet.nmconnection
RUN chmod 600 /etc/NetworkManager/system-connections/server-ethernet.nmconnection
